dist: bionic
sudo: required
language: python
python:
  - "3.7"
addons:
  apt:
    update: true
    packages:
    - xvfb
    - x11-apps
    - imagemagick
    - ffmpeg
before_install:
  - sudo bash -x setup.sh
script:
  - bash -x ci/shoot.sh
os:
  - linux
  - osx
